name: bible_parser_example
description: Example app for the Bible Parser Flutter package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bible_parser_flutter:
    path: ../
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/open-bibles/eng-asv.osis.xml
    - assets/open-bibles/eng-kjv.osis.xml
    - assets/open-bibles/eng-web.usfx.xml
